version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "192.168.1.93:53:53/tcp"
      - "192.168.1.93:53:53/udp"
      - "192.168.1.93:5300:80/tcp"
    environment:
      TZ: 'Australia/Perth'
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    env_file: .env
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped